import { ApiProperty } from '@nestjs/swagger';
/**
 * This file generated by Apso.
 */

export class TicketCreate {
  @ApiProperty()
  title: string;
  @ApiProperty()
  description: string;
  @ApiProperty()
  status: string;
  @ApiProperty()
  priority: string;
  @ApiProperty()
  assignee: string;
}

export class Ticket {
  @ApiProperty()
  id: number;
  @ApiProperty()
  title: string;
  @ApiProperty()
  description: string;
  @ApiProperty()
  status: string;
  @ApiProperty()
  priority: string;
  @ApiProperty()
  assignee: string;
}
