import { ApiProperty } from '@nestjs/swagger';
/**
 * This file generated by Apso.
 */

export class AssigneeCreate {
  @ApiProperty()
  name: string;
}

export class Assignee {
  @ApiProperty()
  id: number;
  @ApiProperty()
  name: string;
}
