/**
 * This file generated by Apso.
 */
import { Module } from '@nestjs/common';
import { Status } from './Status.entity';
import { TypeOrmModule } from '@nestjs/typeorm';
import { StatusService } from './Status.service';
import { StatusController } from './Status.controller';

@Module({
  imports: [TypeOrmModule.forFeature([Status])],
  providers: [StatusService],
  exports: [StatusService],
  controllers: [StatusController],
})
export class StatusModule {}
