/**
 * This file generated by Apso.
 */
import { Test, TestingModule } from '@nestjs/testing';
import { Status, StatusCreate } from './dtos/Status.dto';
import { StatusController } from './Status.controller';
import { StatusService } from './Status.service';
import { CrudRequest } from '@nestjsx/crud';

const baseRequest: CrudRequest = {
  parsed: {
    fields: [],
    paramsFilter: [],
    search: {},
    filter: [],
    or: [],
    join: [],
    sort: [],
    authPersist: undefined,
    limit: 10,
    offset: 0,
    page: 1,
    cache: undefined,
  },
  options: {},
};

describe('StatusController', () => {
  let controller: StatusController;
  let spyService: StatusService;

  beforeEach(async () => {
    const ApiServiceProvider = {
      provide: StatusService,
      useFactory: () => ({
        createOne: jest.fn(() => []),
        getOne: jest.fn(() => {}),
      }),
    };
    const module: TestingModule = await Test.createTestingModule({
      controllers: [StatusController],
      providers: [StatusService, ApiServiceProvider],
    }).compile();

    controller = module.get<StatusController>(StatusController);
    spyService = module.get<StatusService>(StatusService);
  });

  it('should be defined', () => {
    expect(controller).toBeDefined();
  });

  it('should call StatusController get method', () => {
    const req: CrudRequest = { ...baseRequest };
    expect(controller.get(req)).not.toEqual(null);
    expect(spyService.getOne).toHaveBeenCalled();
  });

  it('should call StatusController create method', () => {
    const req: CrudRequest = { ...baseRequest };

    const dto = new Status();
    controller.create(req, dto);
    expect(controller.create(req, dto)).not.toEqual(null);
    expect(spyService.createOne).toHaveBeenCalled();
  });

  // Add your tests here
});
