/**
 * This file generated by Apso.
 */
import { TicketModule } from './Ticket/Ticket.module';
import { StatusModule } from './Status/Status.module';
import { PriorityModule } from './Priority/Priority.module';
import { AssigneeModule } from './Assignee/Assignee.module';

export default [TicketModule, StatusModule, PriorityModule, AssigneeModule];
