/**
 * This file generated by Apso.
 */
import { Module } from '@nestjs/common';
import { Ticket } from './Ticket.entity';
import { TypeOrmModule } from '@nestjs/typeorm';
import { TicketService } from './Ticket.service';
import { TicketController } from './Ticket.controller';

@Module({
  imports: [TypeOrmModule.forFeature([Ticket])],
  providers: [TicketService],
  exports: [TicketService],
  controllers: [TicketController],
})
export class TicketModule {}
