/**
 * This file generated by Apso.
 */
import { Module } from '@nestjs/common';
import { Assignee } from './Assignee.entity';
import { TypeOrmModule } from '@nestjs/typeorm';
import { AssigneeService } from './Assignee.service';
import { AssigneeController } from './Assignee.controller';

@Module({
  imports: [TypeOrmModule.forFeature([Assignee])],
  providers: [AssigneeService],
  exports: [AssigneeService],
  controllers: [AssigneeController],
})
export class AssigneeModule {}
