/**
 * This file generated by Apso.
 */
import { Test, TestingModule } from '@nestjs/testing';
import { Assignee, AssigneeCreate } from './dtos/Assignee.dto';
import { AssigneeController } from './Assignee.controller';
import { AssigneeService } from './Assignee.service';
import { CrudRequest } from '@nestjsx/crud';

const baseRequest: CrudRequest = {
  parsed: {
    fields: [],
    paramsFilter: [],
    search: {},
    filter: [],
    or: [],
    join: [],
    sort: [],
    authPersist: undefined,
    limit: 10,
    offset: 0,
    page: 1,
    cache: undefined,
  },
  options: {},
};

describe('AssigneeController', () => {
  let controller: AssigneeController;
  let spyService: AssigneeService;

  beforeEach(async () => {
    const ApiServiceProvider = {
      provide: AssigneeService,
      useFactory: () => ({
        createOne: jest.fn(() => []),
        getOne: jest.fn(() => {}),
      }),
    };
    const module: TestingModule = await Test.createTestingModule({
      controllers: [AssigneeController],
      providers: [AssigneeService, ApiServiceProvider],
    }).compile();

    controller = module.get<AssigneeController>(AssigneeController);
    spyService = module.get<AssigneeService>(AssigneeService);
  });

  it('should be defined', () => {
    expect(controller).toBeDefined();
  });

  it('should call AssigneeController get method', () => {
    const req: CrudRequest = { ...baseRequest };
    expect(controller.get(req)).not.toEqual(null);
    expect(spyService.getOne).toHaveBeenCalled();
  });

  it('should call AssigneeController create method', () => {
    const req: CrudRequest = { ...baseRequest };

    const dto = new Assignee();
    controller.create(req, dto);
    expect(controller.create(req, dto)).not.toEqual(null);
    expect(spyService.createOne).toHaveBeenCalled();
  });

  // Add your tests here
});
