import { ApiProperty } from '@nestjs/swagger';
/**
 * This file generated by Apso.
 */

export class PriorityCreate {
  @ApiProperty()
  level: string;
}

export class Priority {
  @ApiProperty()
  id: number;
  @ApiProperty()
  level: string;
}
