/**
 * This file generated by Apso.
 */
import { Test, TestingModule } from '@nestjs/testing';
import { Priority, PriorityCreate } from './dtos/Priority.dto';
import { PriorityController } from './Priority.controller';
import { PriorityService } from './Priority.service';
import { CrudRequest } from '@nestjsx/crud';

const baseRequest: CrudRequest = {
  parsed: {
    fields: [],
    paramsFilter: [],
    search: {},
    filter: [],
    or: [],
    join: [],
    sort: [],
    authPersist: undefined,
    limit: 10,
    offset: 0,
    page: 1,
    cache: undefined,
  },
  options: {},
};

describe('PriorityController', () => {
  let controller: PriorityController;
  let spyService: PriorityService;

  beforeEach(async () => {
    const ApiServiceProvider = {
      provide: PriorityService,
      useFactory: () => ({
        createOne: jest.fn(() => []),
        getOne: jest.fn(() => {}),
      }),
    };
    const module: TestingModule = await Test.createTestingModule({
      controllers: [PriorityController],
      providers: [PriorityService, ApiServiceProvider],
    }).compile();

    controller = module.get<PriorityController>(PriorityController);
    spyService = module.get<PriorityService>(PriorityService);
  });

  it('should be defined', () => {
    expect(controller).toBeDefined();
  });

  it('should call PriorityController get method', () => {
    const req: CrudRequest = { ...baseRequest };
    expect(controller.get(req)).not.toEqual(null);
    expect(spyService.getOne).toHaveBeenCalled();
  });

  it('should call PriorityController create method', () => {
    const req: CrudRequest = { ...baseRequest };

    const dto = new Priority();
    controller.create(req, dto);
    expect(controller.create(req, dto)).not.toEqual(null);
    expect(spyService.createOne).toHaveBeenCalled();
  });

  // Add your tests here
});
