/**
 * This file generated by Apso.
 */
import { Module } from '@nestjs/common';
import { Priority } from './Priority.entity';
import { TypeOrmModule } from '@nestjs/typeorm';
import { PriorityService } from './Priority.service';
import { PriorityController } from './Priority.controller';

@Module({
  imports: [TypeOrmModule.forFeature([Priority])],
  providers: [PriorityService],
  exports: [PriorityService],
  controllers: [PriorityController],
})
export class PriorityModule {}
