import { ApiProperty } from '@nestjs/swagger';
/**
 * This file generated by Apso.
 */

export class StatusCreate {
  @ApiProperty()
  name: string;
}

export class Status {
  @ApiProperty()
  id: number;
  @ApiProperty()
  name: string;
}
